site_name: CiviSEPA
site_description: SEPA Direct Debit Extension
repo_url: https://github.com/Project60/org.project60.sepa
theme: material

nav:
- Introduction: index.md
- From a user perspective: user-perspective.md
- A basic configuration that will work: config-example.md
- Terminology: terminology.md
- How To Guide: how-to.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
