version: 2.1
commands:
  setup:
    description: "Setup environment"
    steps:
      - run: |
          composer self-update --1
  install_civicrm:
    description: "Install CiviCRM"
    parameters:
      build_name:
        type: string
        default: master
      type:
        type: string
        default: drupal-clean
      version:
        type: string
        default: master
      url:
        type: string
        default: http://localhost:8080
    steps:
      - run: |
          civiver=<< parameters.version >>
          if [[ "$civiver" == "stable" ]]; then
            civiver=$(curl -s 'https://latest.civicrm.org/stable.php')
          fi
          su - buildkit -c "/buildkit/bin/civibuild create << parameters.build_name >> --civi-ver $civiver --type << parameters.type >> --url << parameters.url >>"
  install_dependencies:
    description: "Install Dependencies"
    parameters:
      build_name:
        type: string
        default: master
    steps:
      - run: |
          EXT_DIR=/buildkit/build/<< parameters.build_name >>/web/sites/default/files/civicrm/ext
          cd $EXT_DIR
  install_extension:
    description: "Install Extension"
    parameters:
      build_name:
        type: string
        default: master
    steps:
      - run: |
          EXT_DIR=/buildkit/build/<< parameters.build_name >>/web/sites/default/files/civicrm/ext/$CIRCLE_PROJECT_REPONAME
          cp /root/project $EXT_DIR -r
          chown buildkit:buildkit $EXT_DIR -R
          cd $EXT_DIR
          su - buildkit -c "cd /buildkit/build/<< parameters.build_name >>/web && cv en $CIRCLE_PROJECT_REPONAME"
  run_civilint:
    description: "Run civilint"
    parameters:
      build_name:
        type: string
        default: master
    steps:
      - run: su - buildkit -c "cd /buildkit/build/<< parameters.build_name >>/web/sites/default/files/civicrm/ext/$CIRCLE_PROJECT_REPONAME && find . -type f -not -path './vendor/*' | civilint"
  run_phpunit:
    description: "Run PHPUnit"
    parameters:
      build_name:
        type: string
        default: master
    steps:
      - run: |
          mkdir -p /phpunit
          chown buildkit:buildkit /phpunit
          su - buildkit -c "cd /buildkit/build/<< parameters.build_name >>/web/sites/default/files/civicrm/ext/$CIRCLE_PROJECT_REPONAME && /buildkit/bin/phpunit6 --log-junit /phpunit/<< parameters.build_name >>/junit.xml"
  run_all:
    description: "Run all steps"
    parameters:
      build_name:
        type: string
        default: master
      type:
        type: string
        default: drupal-clean
      version:
        type: string
        default: master
      url:
        type: string
        default: http://localhost:8080
    steps:
      - install_civicrm:
          build_name: << parameters.build_name >>
          type: << parameters.type >>
          version: << parameters.version >>
          url: << parameters.url >>
      - install_dependencies:
          build_name: << parameters.build_name >>
      - install_extension:
          build_name: << parameters.build_name >>
      - run_civilint:
          build_name: << parameters.build_name >>
      - run_phpunit:
          build_name: << parameters.build_name >>
      - store_test_results:
          path: /phpunit
      - store_artifacts:
          path: /phpunit

executors:
  civicrm:
    docker:
      - image: michaelmcandrew/civicrm-buildkit
        name: civicrm
        environment:
          TERM: xterm-color
          APACHE_RUN_USER: buildkit
      - image: mysql:5.7
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: buildkit

jobs:
  build_mysql_5_7:
    executor: civicrm
    steps:
      - checkout
      - run_all
      - run_all:
          build_name: civi-stable
          version: "stable"
          url: http://localhost:8081
      - run_all:
          build_name: civi-5.50.4
          version: "5.50.4"
          url: http://localhost:8082
  build_mariadb_10_4:
    executor: civicrm
    docker:
      - image: michaelmcandrew/civicrm-buildkit
        name: civicrm
        environment:
          TERM: xterm-color
          APACHE_RUN_USER: buildkit
      - image: mariadb:10.4
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: buildkit
    steps:
      - checkout
      - run_all
      - run_all:
          build_name: civi-stable
          version: "stable"
          url: http://localhost:8081
      - run_all:
          build_name: civi-5.50.4
          version: "5.50.4"
          url: http://localhost:8082
workflows:
  version: 2
  build:
    jobs:
      - build_mysql_5_7
      - build_mariadb_10_4
